// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UploadProject.Data;

#nullable disable

namespace UploadProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("UploadProject.Models.AdminUploadedFile", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompetitionSessionID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("CompetitionSessionID");

                    b.HasIndex("UserID");

                    b.ToTable("AdminUploadedFiles");
                });

            modelBuilder.Entity("UploadProject.Models.CompetitionSession", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DayNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("CompetitionSessions");
                });

            modelBuilder.Entity("UploadProject.Models.CompetitorUploadedFile", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompetitionSessionID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("CompetitionSessionID");

                    b.HasIndex("UserID");

                    b.ToTable("CompetitorUploadedFiles");
                });

            modelBuilder.Entity("UploadProject.Models.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CompetitionSessionID")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("CompetitionSessionID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = new Guid("e0361d0e-802a-4d76-9340-472ba2aa7085"),
                            IsAdmin = true,
                            Password = "WeLoveITSSBIndonesia",
                            Username = "admin"
                        },
                        new
                        {
                            ID = new Guid("60f61f1a-37f9-4a80-815f-6ed58c14cfdc"),
                            IsAdmin = true,
                            Password = "WeLoveITSSBIndonesia",
                            Username = "admin2"
                        },
                        new
                        {
                            ID = new Guid("e7ecd0bf-8a21-4e26-8d4a-2b8af03920a4"),
                            IsAdmin = false,
                            Password = "CMDEKHWQ",
                            Username = "PC01"
                        },
                        new
                        {
                            ID = new Guid("4835bc59-ea3a-4ed5-9940-f26a0cd2fe83"),
                            IsAdmin = false,
                            Password = "MAPZ589U",
                            Username = "PC02"
                        },
                        new
                        {
                            ID = new Guid("a0e85403-18d9-459a-b189-6debe8f2dea3"),
                            IsAdmin = false,
                            Password = "4V1QZNSM",
                            Username = "PC03"
                        },
                        new
                        {
                            ID = new Guid("5c681d9e-462b-463e-9bca-9f392899f0d2"),
                            IsAdmin = false,
                            Password = "9L0NT7J6",
                            Username = "PC04"
                        },
                        new
                        {
                            ID = new Guid("ea585224-eada-491e-9b80-190b7a52117e"),
                            IsAdmin = false,
                            Password = "LXUT0S7W",
                            Username = "PC05"
                        },
                        new
                        {
                            ID = new Guid("535514c1-c065-40c5-9ff1-e8c8c6e3d947"),
                            IsAdmin = false,
                            Password = "OET5HN6R",
                            Username = "PC06"
                        },
                        new
                        {
                            ID = new Guid("fe8634b3-1fd4-46aa-9bae-c63766eff35e"),
                            IsAdmin = false,
                            Password = "O7F3MYLH",
                            Username = "PC07"
                        },
                        new
                        {
                            ID = new Guid("5e46d995-2fee-49d6-9dff-72392b9df935"),
                            IsAdmin = false,
                            Password = "IRO5MEU4",
                            Username = "PC08"
                        },
                        new
                        {
                            ID = new Guid("b543ccce-c16a-4797-8936-d64d3df9353e"),
                            IsAdmin = false,
                            Password = "DXNQ85HY",
                            Username = "PC09"
                        },
                        new
                        {
                            ID = new Guid("8356b83a-b5bc-4ec4-ba47-d0c8017519d4"),
                            IsAdmin = false,
                            Password = "03WO26X7",
                            Username = "PC10"
                        },
                        new
                        {
                            ID = new Guid("0b1eb367-f5fd-4b3f-a890-2d4b6a88035e"),
                            IsAdmin = false,
                            Password = "5X4T08WY",
                            Username = "PC11"
                        },
                        new
                        {
                            ID = new Guid("b98e5dda-3f06-4350-a5d1-8a3faf3a29cb"),
                            IsAdmin = false,
                            Password = "YRZ26PHQ",
                            Username = "PC12"
                        },
                        new
                        {
                            ID = new Guid("74d8840d-37e8-4f9f-af13-781a404a2e60"),
                            IsAdmin = false,
                            Password = "6WXAIYDM",
                            Username = "PC13"
                        },
                        new
                        {
                            ID = new Guid("bdc5aad5-4b53-4267-83de-ef0ee6a8e7db"),
                            IsAdmin = false,
                            Password = "D0B8QOAC",
                            Username = "PC14"
                        },
                        new
                        {
                            ID = new Guid("804bfed2-b00e-4de6-970a-d85df702d096"),
                            IsAdmin = false,
                            Password = "DK8JBW2F",
                            Username = "PC15"
                        },
                        new
                        {
                            ID = new Guid("96c63313-34ff-46eb-bbcb-6df260ac3353"),
                            IsAdmin = false,
                            Password = "D0T7BR45",
                            Username = "PC16"
                        },
                        new
                        {
                            ID = new Guid("7622e89e-c91c-4e19-b501-93e15db40a49"),
                            IsAdmin = false,
                            Password = "TOKJ97QY",
                            Username = "PC17"
                        },
                        new
                        {
                            ID = new Guid("d8faee54-b490-46ac-a5d8-8e585d7095b7"),
                            IsAdmin = false,
                            Password = "EOAWVF2S",
                            Username = "PC18"
                        },
                        new
                        {
                            ID = new Guid("ec99a87f-af1e-476d-ae30-bdd503d7f1d8"),
                            IsAdmin = false,
                            Password = "PAMHRQZ9",
                            Username = "PC19"
                        },
                        new
                        {
                            ID = new Guid("f174ffb0-7ebd-4e47-a93c-693d1297afe6"),
                            IsAdmin = false,
                            Password = "RCHNOMES",
                            Username = "PC20"
                        },
                        new
                        {
                            ID = new Guid("8912e9d7-5e60-4887-9036-af512b4cd952"),
                            IsAdmin = false,
                            Password = "KHONGFR1",
                            Username = "PC21"
                        },
                        new
                        {
                            ID = new Guid("faa4561d-e29a-4b6d-bf12-fec8b267595f"),
                            IsAdmin = false,
                            Password = "1U0G2TVS",
                            Username = "PC22"
                        },
                        new
                        {
                            ID = new Guid("416dae84-9294-4a8a-9d8d-327d74a8d58c"),
                            IsAdmin = false,
                            Password = "G6BE73YX",
                            Username = "PC23"
                        },
                        new
                        {
                            ID = new Guid("abf1b37e-2b48-4dfb-9c3a-411c5768b356"),
                            IsAdmin = false,
                            Password = "Q4CLJXNA",
                            Username = "PC24"
                        },
                        new
                        {
                            ID = new Guid("12cf9dce-243f-41e9-bff1-7bf07b7a8408"),
                            IsAdmin = false,
                            Password = "C0HUZ8NP",
                            Username = "PC25"
                        },
                        new
                        {
                            ID = new Guid("c2847c71-1b7b-4928-ab40-ee01a894e0c8"),
                            IsAdmin = false,
                            Password = "RFXISE9Y",
                            Username = "PC26"
                        },
                        new
                        {
                            ID = new Guid("ce0c33ea-e7de-47ed-847a-bb9c041a2f57"),
                            IsAdmin = false,
                            Password = "S5ETJOVY",
                            Username = "PC27"
                        },
                        new
                        {
                            ID = new Guid("3dc59819-96a2-4882-9e50-117351e81d12"),
                            IsAdmin = false,
                            Password = "WSBX85UP",
                            Username = "PC28"
                        },
                        new
                        {
                            ID = new Guid("9c94e7de-2d7e-4731-a290-e76a18b04dfb"),
                            IsAdmin = false,
                            Password = "6TBONRF5",
                            Username = "PC29"
                        },
                        new
                        {
                            ID = new Guid("ebbfa0ac-bf17-48bc-843b-c97f710ee570"),
                            IsAdmin = false,
                            Password = "Q7F0XK1R",
                            Username = "PC30"
                        },
                        new
                        {
                            ID = new Guid("886bf770-912e-408b-8e0a-209d7434f98d"),
                            IsAdmin = false,
                            Password = "UT69WXCE",
                            Username = "PC31"
                        },
                        new
                        {
                            ID = new Guid("ceb01e02-988b-46f7-b63e-d1595429996c"),
                            IsAdmin = false,
                            Password = "U1FGBK6J",
                            Username = "PC32"
                        },
                        new
                        {
                            ID = new Guid("89d8e81f-2e2b-41fb-8171-0c228373e5e5"),
                            IsAdmin = false,
                            Password = "6AQWOM0J",
                            Username = "PC33"
                        },
                        new
                        {
                            ID = new Guid("6c5e698d-3fb5-4d80-9021-83e8de71009f"),
                            IsAdmin = false,
                            Password = "5K0CPONL",
                            Username = "PC34"
                        },
                        new
                        {
                            ID = new Guid("5ad361ae-25ee-4cb8-a254-3123c7a7e771"),
                            IsAdmin = false,
                            Password = "VBU8HQT1",
                            Username = "PC35"
                        },
                        new
                        {
                            ID = new Guid("f0fc9903-126a-41f3-bd5b-404185a166fa"),
                            IsAdmin = false,
                            Password = "W1UZB0PA",
                            Username = "PC36"
                        },
                        new
                        {
                            ID = new Guid("e0f799aa-ab5c-40af-8977-18037acb9f1f"),
                            IsAdmin = false,
                            Password = "PWDY61MX",
                            Username = "PC37"
                        },
                        new
                        {
                            ID = new Guid("0b42e173-dab6-4c59-af4d-3a2136f8c805"),
                            IsAdmin = false,
                            Password = "B8Q1S2VY",
                            Username = "PC38"
                        },
                        new
                        {
                            ID = new Guid("dbbf0200-82f7-4238-86c5-dc04ed174ff1"),
                            IsAdmin = false,
                            Password = "RYONL1GA",
                            Username = "PC39"
                        },
                        new
                        {
                            ID = new Guid("7a2ebe98-f6fe-455e-9755-b48fc2da28dc"),
                            IsAdmin = false,
                            Password = "YXINWEJA",
                            Username = "PC40"
                        },
                        new
                        {
                            ID = new Guid("a1f84658-5b47-449e-b258-9ca09fcde852"),
                            IsAdmin = false,
                            Password = "DXB52JZF",
                            Username = "PC41"
                        },
                        new
                        {
                            ID = new Guid("c431d81f-883c-41d5-aedf-d418bf71fc14"),
                            IsAdmin = false,
                            Password = "0GKB7E59",
                            Username = "PC42"
                        },
                        new
                        {
                            ID = new Guid("6068faa6-6acd-44ef-9e00-b398addf2fa8"),
                            IsAdmin = false,
                            Password = "3ZGOUNMJ",
                            Username = "PC43"
                        },
                        new
                        {
                            ID = new Guid("f6c952c5-7431-4f52-a087-59f38f8b1d0f"),
                            IsAdmin = false,
                            Password = "N6VZPO1S",
                            Username = "PC44"
                        },
                        new
                        {
                            ID = new Guid("14095725-9dd0-443c-831f-5d9068ceb244"),
                            IsAdmin = false,
                            Password = "VBY3AGX0",
                            Username = "PC45"
                        },
                        new
                        {
                            ID = new Guid("c2aa716f-ebd9-4a0f-87e2-c1d8ee60ad52"),
                            IsAdmin = false,
                            Password = "P2748RFB",
                            Username = "PC46"
                        },
                        new
                        {
                            ID = new Guid("b8472993-df58-4715-aeda-137a39d54801"),
                            IsAdmin = false,
                            Password = "05AKG8S1",
                            Username = "PC47"
                        },
                        new
                        {
                            ID = new Guid("d7e5db0c-f5d9-44c4-8c8a-36e4adee3ae9"),
                            IsAdmin = false,
                            Password = "AHEOTSKL",
                            Username = "PC48"
                        },
                        new
                        {
                            ID = new Guid("cfc6c7ed-6213-4f00-823c-c76b420b59bb"),
                            IsAdmin = false,
                            Password = "Q2E0FUX3",
                            Username = "PC49"
                        },
                        new
                        {
                            ID = new Guid("b0d4304b-681f-4da4-a839-d4bddc91b838"),
                            IsAdmin = false,
                            Password = "4EKD5JU0",
                            Username = "PC50"
                        });
                });

            modelBuilder.Entity("UploadProject.Models.AdminUploadedFile", b =>
                {
                    b.HasOne("UploadProject.Models.CompetitionSession", "CompetitionSession")
                        .WithMany()
                        .HasForeignKey("CompetitionSessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UploadProject.Models.User", "User")
                        .WithMany("AdminUploadedFiles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetitionSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UploadProject.Models.CompetitorUploadedFile", b =>
                {
                    b.HasOne("UploadProject.Models.CompetitionSession", "CompetitionSession")
                        .WithMany()
                        .HasForeignKey("CompetitionSessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UploadProject.Models.User", "User")
                        .WithMany("CompetitorUploadedFiles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetitionSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UploadProject.Models.User", b =>
                {
                    b.HasOne("UploadProject.Models.CompetitionSession", null)
                        .WithMany("Competitors")
                        .HasForeignKey("CompetitionSessionID");
                });

            modelBuilder.Entity("UploadProject.Models.CompetitionSession", b =>
                {
                    b.Navigation("Competitors");
                });

            modelBuilder.Entity("UploadProject.Models.User", b =>
                {
                    b.Navigation("AdminUploadedFiles");

                    b.Navigation("CompetitorUploadedFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
